parser: '@typescript-eslint/parser'

parserOptions:
  ecmaVersion: 12
  sourceType: module

env:
  es2021: true
  node: true

plugins:
  - '@typescript-eslint'
  - import

extends:
  - plugin:@typescript-eslint/recommended
  - prettier

rules: 
  no-console: 0
  import/prefer-default-export: 0
  import/no-default-export: 1
